name = "macOS Commands"

[on.keys]
file = "keys.js"

[chords]
'?,' = { name = "Commands / Modifier Keys" }

'?,a' = { name = "Alt" }
',(a[cfms]*-.*)' = { name = "Alt Combo", 'emit:keys' = ['$1'] }

'?,c' = { name = "Ctrl" }
',(c[fms]*-.*)' = { name = "Ctrl Combo", 'emit:keys' = ['$1'] }

'?,f' = { name = "Fn" }
',(f[ms]*-.*)' = { name = "Fn Combo", 'emit:keys' = ['$1'] }

'?,m' = { name = "Meta (Cmd)" }
',(m[s]*-.*)' = { name = "Meta (Cmd) Combo", 'emit:keys' = ['$1'] }

'?,s' = { name = "Shift" }
',(s-.*)' = { name = "Shift Combo", 'emit:keys' = ['$1'] }

'?,-' = { name = "Unmodified Key" }
',(-.*)' = { name = "Unmodified key", 'emit:keys' = ['$1'] }
