name = "Windows Commands"

[chords]
'?,' = { name = "Universal Commands" }
',a' = { name = "Select All", shortcut = "ctrl+a" }
',s' = { name = "Save", shortcut = "ctrl+s" }
',f' = { name = "Find", shortcut = "ctrl+f" }
',h' = { name = "Hide", shortcut = "ctrl+h" }
',r' = { name = "Refresh", shortcut = "ctrl+r" }
',z' = { name = "Undo", shortcut = "ctrl+z" }
',y' = { name = "Redo", shortcut = "ctrl+y" }
',x' = { name = "Cut", shortcut = "ctrl+x" }
',c' = { name = "Copy", shortcut = "ctrl+c" }
',v' = { name = "Paste", shortcut = "ctrl+v" }
',o' = { name = "Open", shortcut = "ctrl+o" }
',n' = { name = "New", shortcut = "ctrl+n" }
',m' = { name = "Minimize", shortcut = "ctrl+m" }
',[' = { name = "Back", shortcut = "ctrl+[" }
',]' = { name = "Forward", shortcut = "ctrl+]" }
',q' = { name = "Quit", shortcut = "ctrl+q" }
',w' = { name = "Close", shortcut = "ctrl+w" }
',,' = { name = "Settings", shortcut = "ctrl+," }
',=' = { name = "Zoom In", shortcut = "ctrl+=" }
',-' = { name = "Zoom Out", shortcut = "ctrl+-" }
